name: http_logger_plus
description: >
  A developer-friendly HTTP logger for Dart and Flutter that wraps http.Client and logs
  all requests and responses with cURL generation, pretty formatting, and color-coded output.
version: 1.0.0
repository: https://github.com/WannaCry016/http_logger_plus
homepage: https://github.com/WannaCry016/http_logger_plus
issue_tracker: https://github.com/WannaCry016/http_logger_plus/issues
documentation: https://github.com/WannaCry016/http_logger_plus#readme

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# Optional: include topics (used on pub.dev)
topics:
  - http
  - logging
  - developer-tools
  - curl
  - debug
